name: CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  tests-backend:
    name: Unit tests - Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Run Tests
        run: mvn -B test
  
  #tests-frontend:
  #  name: Unit tests - Frontend
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v4
  #    - name: Set up Node.js
  #      uses: actions/setup-node@v2
  #      with:
  #        node-version: '14'
  #
  #    - name: Install dependencies
  #      run: npm install
  #    
  #    - name: Run Jest tests
  #      run: npm test

  build:
    needs: tests-backend
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml
      - run: mkdir staging && cp target/*.jar staging